name: Auto-label when user responds
permissions:
  issues: write
  pull-requests: write
  discussions: write

on:
  issue_comment:
    types: [created]

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Add/remove labels when user responds
        uses: weibullguy/labeler@master
        # if: ${{ github.event.comment.user.login == github.event.issue.user.login && contains(github.event.issue.labels.*.name, 'wait-for-author') && !contains(github.event.issue.labels.*.name, 'author-responded') }}
        if: ${{ github.event.comment.user.login == github.event.issue.user.login && contains(github.event.issue.labels.*.name, 'wait-for-author') }}
        with:
          # add-labels: 'author-responded'
          remove-labels: 'wait-for-author'
